still trying

diff --git a/.github/workflows/mac_11.yml b/.github/workflows/mac_11.yml
--- a/.github/workflows/mac_11.yml
+++ b/.github/workflows/mac_11.yml
@@ -76,7 +76,9 @@ jobs:
           ls -l ${{env.MAGICK_HOME}}/bin/
 
       - name: Install create-dmg
-        run: npm install --global create-dmg
+        run: |
+          npm cache clean --force
+          npm install --global create-dmg
 
       - name: Add Python 3.11 to PATH
         run: export PATH=/usr/local/Cellar/python@3.11/bin:$PATH
@@ -101,7 +103,13 @@ jobs:
           echo "DYLD_LIBRARY_PATH = ${{env.DYLD_LIBRARY_PATH}}"
           echo "PATH = ${{env.PATH}}"
           ls -l ${{env.MAGICK_HOME}}/bin/
-          ./build.sh
+          ./build.sh || echo "Build failed, creating artifacts from PixelFlasher.app" && exit 1
+        if: ${{ failure() }}
+      - name: Upload PixelFlasher.app as artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: PixelFlasher.app
+          path: dist/PixelFlasher.app
 
       - name: Rename the file
         run: mv dist/PixelFlasher.dmg dist/PixelFlasher_MacOS_11.dmg
diff --git a/.github/workflows/mac_13.yml b/.github/workflows/mac_13.yml
--- a/.github/workflows/mac_13.yml
+++ b/.github/workflows/mac_13.yml
@@ -107,7 +107,13 @@ jobs:
           echo "DYLD_LIBRARY_PATH = ${{env.DYLD_LIBRARY_PATH}}"
           echo "PATH = ${{env.PATH}}"
           ls -l ${{env.MAGICK_HOME}}/bin/
-          ./build.sh
+          ./build.sh || echo "Build failed, creating artifacts from PixelFlasher.app" && exit 1
+        if: ${{ failure() }}
+      - name: Upload PixelFlasher.app as artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: PixelFlasher.app
+          path: dist/PixelFlasher.app
 
       - name: Rename the file
         run: mv dist/PixelFlasher.dmg dist/PixelFlasher_MacOS_13.dmg
