Use Python 13 arm64

diff --git a/.github/workflows/windows-arm64.yml b/.github/workflows/windows-arm64.yml
--- a/.github/workflows/windows-arm64.yml
+++ b/.github/workflows/windows-arm64.yml
@@ -46,11 +46,11 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.12'
-          # Using x64 Python for cross-compilation
+      - name: Download ARM64 Python
+        shell: pwsh
+        run: |
+          curl https://www.python.org/ftp/python/3.13.0/python-3.13.0-arm64.exe --output python-arm64.exe
+          ./python-arm64.exe /quiet InstallAllUsers=1 PrependPath=1
 
       - name: Install Windows SDK
         uses: GuillaumeFalourd/setup-windows10-sdk-action@v1
@@ -91,6 +91,14 @@ jobs:
         shell: cmd
         run: pyinstaller --log-level=DEBUG --clean --noconfirm build-on-win-arm64.spec
 
+      - name: Verify Output Exists
+        shell: pwsh
+        run: |
+          if (!(Test-Path "dist/PixelFlasher-arm64.exe")) {
+            Write-Error "ARM64 executable not found"
+            exit 1
+          }
+
       - name: Sign Windows ARM64 Executable
         uses: skymatic/code-sign-action@v3
         with:
@@ -104,14 +112,10 @@ jobs:
           recursive: false
 
       - name: Generate SHA256
+        shell: pwsh
         run: |
-          certutil -hashfile dist/PixelFlasher.exe SHA256 > dist/PixelFlasher-arm64.exe.sha256
-          cat dist/PixelFlasher-arm64.exe.sha256
-        shell: pwsh
-
-      - name: Rename executable
-        run: Move-Item dist/PixelFlasher.exe dist/PixelFlasher-arm64.exe
-        shell: pwsh
+          Get-FileHash "dist/PixelFlasher-arm64.exe" -Algorithm SHA256 | Select-Object -ExpandProperty Hash > dist/PixelFlasher-arm64.exe.sha256
+          Get-Content dist/PixelFlasher-arm64.exe.sha256
 
       - name: Upload ARM64 Artifacts
         uses: actions/upload-artifact@v4
@@ -120,3 +124,4 @@ jobs:
           path: |
             dist/PixelFlasher-arm64.exe
             dist/PixelFlasher-arm64.exe.sha256
+
